version: '3.9'

services:
  app:
    container_name: resti-app
    build: .
    image: resti-app
    restart: always
    tty: true
    expose:
      - '8000:8000'
    ports:
      - '8000:8000'
    networks:
      - api
    depends_on:
      - database
  database:
    image: postgres:15.4-alpine
    container_name: resti-database
    restart: always
    tty: true
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - '5432:5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - api

volumes:
  postgres:
    driver: local
  app-resti:
    driver: local


networks:
  api:
    driver: bridge

